### ISSUE TITLE
Add BloodDPS

### ISSUE THREAD

**Issue by Serverfrog** [Hellixoid/BistooltipAddon#1]
Due to the fact that Blood DPS is since ToC fixed, so it will do good amount of Damage. It would be good to add this.
As i know that a good amount of Guilds uses this tool into their Loot Rules, a Blood DPS will be excluded from that and need special handling.

Also it will help them.

The BiS list from WoWHead: https://www.wowhead.com/wotlk/guide/classes/death-knight/blood/dps-bis-gear-pve-phase-4
From wowtbc: https://wowtbc.gg/wotlk/bis-list/blood-dps-death-knight/

**Comment by Hellixoid** [comment]
Added in v7.35

**Comment by Serverfrog** [comment]
Thank you! but i found a little bug in there. It seems the Horde to Alliance Conversion of Items is not done there,  as the Dual-Blade Butcher is not a Alliance weapon ;) (should be justicebringer, as for the Fury Warrior)
