### ISSUE TITLE
Cata Classic support

### ISSUE THREAD

**Issue by drcrazy** [Hellixoid/BistooltipAddon#7]
Hello. 

First of all, thank you for a nice mod which helps a lot on loot priority!

Do you have any plans to update it to Cata Classic? BiS list are already there both on wowtbc.gg and wowhead.com.

Thank you in adnvance!

**Comment by Hellixoid** [comment]
I'm planning to start working on a Cata version after all the bis lists are published. As I can see, they only released pre-patch bis lists on wowhead atm.

**Comment by drcrazy** [comment]
Fair enough. Looking forward for updated version.
