### ISSUE TITLE
Update for Cata?

### ISSUE THREAD

**Issue by Raina1007** [Hellixoid/BistooltipAddon#8]
Just wanted to confirm if this addon would be updated for Cata Classic or no. I get it, people's lives get crazy and passion projects have to put to the side. Was just wondering, either way thank you for the awesome addon through Wrath Classic!

**Comment by drcrazy** [comment]
Author is waiting for BiS lists on wowhead as per answer here: #7

**Comment by Raina1007** [comment]
That would be acceptable except if you check my links, they are there. Wowhead just hasn't bothered to do featured article yet. But they are there, just need to know how to navigate the drop down list on the left hand side to find it. 
https://www.wowhead.com/cata/guide/classes/death-knight/blood/tank-bis-gear-pre-raid
https://www.wowhead.com/cata/guide/classes/death-knight/frost
<img width="384" alt="Screenshot 2024-05-20 at 11 59 09 AM" src="https://github.com/Hellixoid/BistooltipAddon/assets/72997449/206beb9e-1b17-4b6f-ae58-1de5b05564ff">
/dps-bis-gear-pre-raid
https://www.wowhead.com/cata/guide/classes/death-knight/unholy/dps-bis-gear-pre-raid
